#!/usr/bin/env bash
NAME="authms"
VERSION="v1"
DESCRIPTION="Authentication Micro-Service"
CANONICAL_NAME="authmsv1"
CONF_DIR="/etc/authms"
CONF_FILE="/etc/authms/authmsv1.conf.yml"
INSTALL_DIR="/usr/local/bin"
INSTALL_FILE="/usr/local/bin/authmsv1"
UNIT_NAME="authmsv1.service"
UNIT_FILE="/etc/systemd/system/authmsv1.service"
TPL_DIR="/etc/authms/templates"
EMAIL_INVITE_TPL="/etc/authms/templates/authmsv1_email_invite.html"
PHONE_INVITE_TPL="/etc/authms/templates/authmsv1_phone_invite.tpl"
EMAIL_RESET_PASS_TPL="/etc/authms/templates/authmsv1_email_reset_pass.html"
PHONE_RESET_PASS_TPL="/etc/authms/templates/authmsv1_phone_reset_pass.tpl"
EMAIL_VERIFY_TPL="/etc/authms/templates/authmsv1_email_verify.html"
PHONE_VERIFY_TPL="/etc/authms/templates/authmsv1_phone_verify.tpl"
