#!/usr/bin/env bash
NAME="authms"
VERSION=""
DESCRIPTION="Authentication Micro-Service"
CANONICAL_NAME="authms"
CONF_DIR="/etc/authms"
CONF_FILE="/etc/authms/authms.conf.yml"
INSTALL_DIR="/usr/local/bin"
INSTALL_FILE="/usr/local/bin/authms"
UNIT_NAME="authms.service"
UNIT_FILE="/etc/systemd/system/authms.service"
