#!/usr/bin/env bash
NAME="authms"
VERSION="v1"
DESCRIPTION="Authentication Micro-Service"
CANONICAL_NAME="authmsv1"
CONF_DIR="/etc/authms"
CONF_FILE="/etc/authms/authmsv1.conf.yml"
INSTALL_DIR="/usr/local/bin"
INSTALL_FILE="/usr/local/bin/authmsv1"
UNIT_NAME="authmsv1.service"
UNIT_FILE="/etc/systemd/system/authmsv1.service"
