// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/tomogoma/authms/api/users.proto

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	github.com/tomogoma/authms/api/users.proto

It has these top-level messages:
	UserName
	UserType
	VerifLogin
	Facebook
	Group
	Device
	User
	GetDetailsReq
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UserName struct {
	ID          string `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
	UserID      string `protobuf:"bytes,2,opt,name=userID" json:"userID,omitempty"`
	Value       string `protobuf:"bytes,3,opt,name=value" json:"value,omitempty"`
	Created     string `protobuf:"bytes,4,opt,name=created" json:"created,omitempty"`
	LastUpdated string `protobuf:"bytes,5,opt,name=lastUpdated" json:"lastUpdated,omitempty"`
}

func (m *UserName) Reset()                    { *m = UserName{} }
func (m *UserName) String() string            { return proto.CompactTextString(m) }
func (*UserName) ProtoMessage()               {}
func (*UserName) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *UserName) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *UserName) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *UserName) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *UserName) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *UserName) GetLastUpdated() string {
	if m != nil {
		return m.LastUpdated
	}
	return ""
}

type UserType struct {
	ID          string `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Created     string `protobuf:"bytes,3,opt,name=created" json:"created,omitempty"`
	LastUpdated string `protobuf:"bytes,4,opt,name=lastUpdated" json:"lastUpdated,omitempty"`
}

func (m *UserType) Reset()                    { *m = UserType{} }
func (m *UserType) String() string            { return proto.CompactTextString(m) }
func (*UserType) ProtoMessage()               {}
func (*UserType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *UserType) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *UserType) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserType) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *UserType) GetLastUpdated() string {
	if m != nil {
		return m.LastUpdated
	}
	return ""
}

type VerifLogin struct {
	ID          string `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
	UserID      string `protobuf:"bytes,2,opt,name=userID" json:"userID,omitempty"`
	Value       string `protobuf:"bytes,3,opt,name=value" json:"value,omitempty"`
	Verified    bool   `protobuf:"varint,4,opt,name=verified" json:"verified,omitempty"`
	Created     string `protobuf:"bytes,5,opt,name=created" json:"created,omitempty"`
	LastUpdated string `protobuf:"bytes,6,opt,name=lastUpdated" json:"lastUpdated,omitempty"`
}

func (m *VerifLogin) Reset()                    { *m = VerifLogin{} }
func (m *VerifLogin) String() string            { return proto.CompactTextString(m) }
func (*VerifLogin) ProtoMessage()               {}
func (*VerifLogin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *VerifLogin) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *VerifLogin) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *VerifLogin) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *VerifLogin) GetVerified() bool {
	if m != nil {
		return m.Verified
	}
	return false
}

func (m *VerifLogin) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *VerifLogin) GetLastUpdated() string {
	if m != nil {
		return m.LastUpdated
	}
	return ""
}

type Facebook struct {
	ID          string `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
	UserID      string `protobuf:"bytes,2,opt,name=userID" json:"userID,omitempty"`
	FacebookID  string `protobuf:"bytes,3,opt,name=facebookID" json:"facebookID,omitempty"`
	Verified    bool   `protobuf:"varint,4,opt,name=verified" json:"verified,omitempty"`
	Created     string `protobuf:"bytes,5,opt,name=created" json:"created,omitempty"`
	LastUpdated string `protobuf:"bytes,6,opt,name=lastUpdated" json:"lastUpdated,omitempty"`
}

func (m *Facebook) Reset()                    { *m = Facebook{} }
func (m *Facebook) String() string            { return proto.CompactTextString(m) }
func (*Facebook) ProtoMessage()               {}
func (*Facebook) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Facebook) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Facebook) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *Facebook) GetFacebookID() string {
	if m != nil {
		return m.FacebookID
	}
	return ""
}

func (m *Facebook) GetVerified() bool {
	if m != nil {
		return m.Verified
	}
	return false
}

func (m *Facebook) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *Facebook) GetLastUpdated() string {
	if m != nil {
		return m.LastUpdated
	}
	return ""
}

type Group struct {
	ID          string  `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
	Name        string  `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	AccessLevel float32 `protobuf:"fixed32,3,opt,name=accessLevel" json:"accessLevel,omitempty"`
	Created     string  `protobuf:"bytes,4,opt,name=created" json:"created,omitempty"`
	LastUpdated string  `protobuf:"bytes,5,opt,name=lastUpdated" json:"lastUpdated,omitempty"`
}

func (m *Group) Reset()                    { *m = Group{} }
func (m *Group) String() string            { return proto.CompactTextString(m) }
func (*Group) ProtoMessage()               {}
func (*Group) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Group) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Group) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Group) GetAccessLevel() float32 {
	if m != nil {
		return m.AccessLevel
	}
	return 0
}

func (m *Group) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *Group) GetLastUpdated() string {
	if m != nil {
		return m.LastUpdated
	}
	return ""
}

type Device struct {
	ID          string `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
	UserID      string `protobuf:"bytes,2,opt,name=userID" json:"userID,omitempty"`
	DeviceID    string `protobuf:"bytes,3,opt,name=deviceID" json:"deviceID,omitempty"`
	Created     string `protobuf:"bytes,4,opt,name=created" json:"created,omitempty"`
	LastUpdated string `protobuf:"bytes,5,opt,name=lastUpdated" json:"lastUpdated,omitempty"`
}

func (m *Device) Reset()                    { *m = Device{} }
func (m *Device) String() string            { return proto.CompactTextString(m) }
func (*Device) ProtoMessage()               {}
func (*Device) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Device) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Device) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *Device) GetDeviceID() string {
	if m != nil {
		return m.DeviceID
	}
	return ""
}

func (m *Device) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *Device) GetLastUpdated() string {
	if m != nil {
		return m.LastUpdated
	}
	return ""
}

type User struct {
	ID          string      `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
	JWT         string      `protobuf:"bytes,2,opt,name=JWT" json:"JWT,omitempty"`
	Type        *UserType   `protobuf:"bytes,3,opt,name=type" json:"type,omitempty"`
	Username    *UserName   `protobuf:"bytes,4,opt,name=username" json:"username,omitempty"`
	Phone       *VerifLogin `protobuf:"bytes,5,opt,name=phone" json:"phone,omitempty"`
	Email       *VerifLogin `protobuf:"bytes,6,opt,name=email" json:"email,omitempty"`
	Facebook    *Facebook   `protobuf:"bytes,7,opt,name=facebook" json:"facebook,omitempty"`
	Groups      []*Group    `protobuf:"bytes,8,rep,name=groups" json:"groups,omitempty"`
	Devices     []*Device   `protobuf:"bytes,9,rep,name=devices" json:"devices,omitempty"`
	Created     string      `protobuf:"bytes,10,opt,name=created" json:"created,omitempty"`
	LastUpdated string      `protobuf:"bytes,11,opt,name=lastUpdated" json:"lastUpdated,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *User) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *User) GetJWT() string {
	if m != nil {
		return m.JWT
	}
	return ""
}

func (m *User) GetType() *UserType {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *User) GetUsername() *UserName {
	if m != nil {
		return m.Username
	}
	return nil
}

func (m *User) GetPhone() *VerifLogin {
	if m != nil {
		return m.Phone
	}
	return nil
}

func (m *User) GetEmail() *VerifLogin {
	if m != nil {
		return m.Email
	}
	return nil
}

func (m *User) GetFacebook() *Facebook {
	if m != nil {
		return m.Facebook
	}
	return nil
}

func (m *User) GetGroups() []*Group {
	if m != nil {
		return m.Groups
	}
	return nil
}

func (m *User) GetDevices() []*Device {
	if m != nil {
		return m.Devices
	}
	return nil
}

func (m *User) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *User) GetLastUpdated() string {
	if m != nil {
		return m.LastUpdated
	}
	return ""
}

type GetDetailsReq struct {
	APIKey string `protobuf:"bytes,1,opt,name=APIKey" json:"APIKey,omitempty"`
	JWT    string `protobuf:"bytes,2,opt,name=JWT" json:"JWT,omitempty"`
	UserID string `protobuf:"bytes,3,opt,name=userID" json:"userID,omitempty"`
}

func (m *GetDetailsReq) Reset()                    { *m = GetDetailsReq{} }
func (m *GetDetailsReq) String() string            { return proto.CompactTextString(m) }
func (*GetDetailsReq) ProtoMessage()               {}
func (*GetDetailsReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *GetDetailsReq) GetAPIKey() string {
	if m != nil {
		return m.APIKey
	}
	return ""
}

func (m *GetDetailsReq) GetJWT() string {
	if m != nil {
		return m.JWT
	}
	return ""
}

func (m *GetDetailsReq) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func init() {
	proto.RegisterType((*UserName)(nil), "api.UserName")
	proto.RegisterType((*UserType)(nil), "api.UserType")
	proto.RegisterType((*VerifLogin)(nil), "api.VerifLogin")
	proto.RegisterType((*Facebook)(nil), "api.Facebook")
	proto.RegisterType((*Group)(nil), "api.Group")
	proto.RegisterType((*Device)(nil), "api.Device")
	proto.RegisterType((*User)(nil), "api.User")
	proto.RegisterType((*GetDetailsReq)(nil), "api.GetDetailsReq")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Users service

type UsersClient interface {
	GetDetails(ctx context.Context, in *GetDetailsReq, opts ...client.CallOption) (*User, error)
}

type usersClient struct {
	c           client.Client
	serviceName string
}

func NewUsersClient(serviceName string, c client.Client) UsersClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "api"
	}
	return &usersClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *usersClient) GetDetails(ctx context.Context, in *GetDetailsReq, opts ...client.CallOption) (*User, error) {
	req := c.c.NewRequest(c.serviceName, "Users.GetDetails", in)
	out := new(User)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Users service

type UsersHandler interface {
	GetDetails(context.Context, *GetDetailsReq, *User) error
}

func RegisterUsersHandler(s server.Server, hdlr UsersHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Users{hdlr}, opts...))
}

type Users struct {
	UsersHandler
}

func (h *Users) GetDetails(ctx context.Context, in *GetDetailsReq, out *User) error {
	return h.UsersHandler.GetDetails(ctx, in, out)
}

func init() { proto.RegisterFile("github.com/tomogoma/authms/api/users.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 511 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x94, 0xdf, 0x8b, 0xd3, 0x40,
	0x10, 0xc7, 0xc9, 0xcf, 0xa6, 0x13, 0x4e, 0x65, 0x11, 0x09, 0x7d, 0x90, 0x5a, 0x38, 0x38, 0x15,
	0x5a, 0xa8, 0xfe, 0x03, 0x42, 0xf0, 0x88, 0x1e, 0xa2, 0xcb, 0x9d, 0x3e, 0x6f, 0xd3, 0xbd, 0x76,
	0x35, 0xe9, 0xc6, 0x6c, 0x52, 0xe8, 0xbb, 0x0f, 0xfa, 0x6f, 0xf8, 0xe8, 0x1f, 0xe8, 0xb3, 0xec,
	0xe4, 0x47, 0x83, 0x39, 0x4a, 0xa1, 0xdc, 0x5b, 0x66, 0xbe, 0xb3, 0x99, 0x4f, 0x66, 0xbe, 0x1b,
	0x78, 0xb1, 0x12, 0xc5, 0xba, 0x5c, 0x4c, 0x63, 0x99, 0xce, 0x0a, 0x99, 0xca, 0x95, 0x4c, 0xd9,
	0x8c, 0x95, 0xc5, 0x3a, 0x55, 0x33, 0x96, 0x89, 0x59, 0xa9, 0x78, 0xae, 0xa6, 0x59, 0x2e, 0x0b,
	0x49, 0x2c, 0x96, 0x89, 0xc9, 0x0f, 0x03, 0xbc, 0x1b, 0xc5, 0xf3, 0x0f, 0x2c, 0xe5, 0xe4, 0x01,
	0x98, 0x51, 0x18, 0x18, 0x63, 0xe3, 0x62, 0x48, 0xcd, 0x28, 0x24, 0x4f, 0xc0, 0xd5, 0x07, 0xa2,
	0x30, 0x30, 0x31, 0x57, 0x47, 0xe4, 0x31, 0x38, 0x5b, 0x96, 0x94, 0x3c, 0xb0, 0x30, 0x5d, 0x05,
	0x24, 0x80, 0x41, 0x9c, 0x73, 0x56, 0xf0, 0x65, 0x60, 0x63, 0xbe, 0x09, 0xc9, 0x18, 0xfc, 0x84,
	0xa9, 0xe2, 0x26, 0x5b, 0xa2, 0xea, 0xa0, 0xda, 0x4d, 0x4d, 0xbe, 0x56, 0x14, 0xd7, 0xbb, 0xac,
	0x4f, 0x41, 0xc0, 0xde, 0xb0, 0x94, 0xd7, 0x0c, 0xf8, 0xdc, 0xed, 0x65, 0x1d, 0xec, 0x65, 0xf7,
	0x7b, 0xfd, 0x36, 0x00, 0x3e, 0xf3, 0x5c, 0xdc, 0x5e, 0xc9, 0x95, 0xd8, 0x9c, 0xf8, 0xd1, 0x23,
	0xf0, 0xb6, 0xfa, 0x5d, 0xa2, 0xee, 0xe5, 0xd1, 0x36, 0xee, 0x42, 0x3a, 0x07, 0x21, 0xdd, 0x3e,
	0xe4, 0x1f, 0x03, 0xbc, 0xb7, 0x2c, 0xe6, 0x0b, 0x29, 0xbf, 0x1d, 0x8d, 0xf8, 0x14, 0xe0, 0xb6,
	0x3e, 0x13, 0x85, 0x35, 0x67, 0x27, 0x73, 0x6f, 0xb0, 0xbf, 0x0c, 0x70, 0x2e, 0x73, 0x59, 0x66,
	0x47, 0xed, 0x6e, 0x0c, 0x3e, 0x8b, 0x63, 0xae, 0xd4, 0x15, 0xdf, 0xf2, 0x04, 0x31, 0x4d, 0xda,
	0x4d, 0x9d, 0xe4, 0xa4, 0x9f, 0x06, 0xb8, 0x21, 0xdf, 0x8a, 0xf8, 0x78, 0x3b, 0x8f, 0xc0, 0x5b,
	0xe2, 0x89, 0x76, 0x68, 0x6d, 0x7c, 0x12, 0xca, 0x5f, 0x13, 0x6c, 0xed, 0xea, 0x1e, 0xc8, 0x23,
	0xb0, 0xde, 0x7d, 0xb9, 0xae, 0x29, 0xf4, 0x23, 0x79, 0x06, 0x76, 0xb1, 0xcb, 0x2a, 0x6f, 0xf9,
	0xf3, 0xb3, 0x29, 0xcb, 0xc4, 0xb4, 0xb9, 0x10, 0x14, 0x25, 0xf2, 0x1c, 0x3c, 0xcd, 0x8b, 0xe3,
	0xb4, 0xff, 0x2b, 0xd3, 0xb7, 0x97, 0xb6, 0x32, 0x39, 0x07, 0x27, 0x5b, 0xcb, 0x0d, 0x47, 0x28,
	0x7f, 0xfe, 0x10, 0xeb, 0xf6, 0x96, 0xa7, 0x95, 0xaa, 0xcb, 0x78, 0xca, 0x44, 0x82, 0x2b, 0xbd,
	0xab, 0x0c, 0x55, 0xdd, 0xb8, 0xf1, 0x50, 0x30, 0xe8, 0x34, 0x6e, 0xec, 0x49, 0x5b, 0x99, 0x4c,
	0xc0, 0x5d, 0x69, 0x1f, 0xa8, 0xc0, 0x1b, 0x5b, 0x17, 0xfe, 0x1c, 0xb0, 0x10, 0xad, 0x41, 0x6b,
	0x85, 0x9c, 0xc3, 0xa0, 0x9a, 0xae, 0x0a, 0x86, 0x58, 0xe4, 0x63, 0x51, 0xb5, 0x33, 0xda, 0x68,
	0xdd, 0xc1, 0xc3, 0xc1, 0xc1, 0xfb, 0xfd, 0xc1, 0x7f, 0x82, 0xb3, 0x4b, 0x5e, 0x84, 0xbc, 0x60,
	0x22, 0x51, 0x94, 0x7f, 0xd7, 0x9b, 0x7f, 0xf3, 0x31, 0x7a, 0xcf, 0x77, 0xf5, 0x12, 0xea, 0xe8,
	0x8e, 0x45, 0xec, 0x3d, 0x62, 0x75, 0x3d, 0x32, 0x7f, 0x0d, 0x8e, 0x1e, 0xb4, 0x22, 0x2f, 0x01,
	0xf6, 0xef, 0x26, 0xa4, 0xfa, 0xc0, 0x6e, 0xb3, 0xd1, 0xb0, 0x5d, 0xcb, 0xc2, 0xc5, 0x3f, 0xed,
	0xab, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xa4, 0xf6, 0x20, 0xa5, 0x97, 0x05, 0x00, 0x00,
}
