// Code generated by protoc-gen-go.
// source: github.com/tomogoma/authms/proto/authms/authms.proto
// DO NOT EDIT!

/*
Package authms is a generated protocol buffer package.

It is generated from these files:
	github.com/tomogoma/authms/proto/authms/authms.proto

It has these top-level messages:
	History
	OAuth
	Value
	User
	BasicAuthRequest
	OAuthRequest
	TokenRequest
	Response
*/
package authms

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type History struct {
	ID            int64  `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	UserID        int64  `protobuf:"varint,2,opt,name=userID" json:"userID,omitempty"`
	IpAddress     string `protobuf:"bytes,3,opt,name=ipAddress" json:"ipAddress,omitempty"`
	Date          string `protobuf:"bytes,4,opt,name=date" json:"date,omitempty"`
	AccessType    string `protobuf:"bytes,5,opt,name=accessType" json:"accessType,omitempty"`
	SuccessStatus bool   `protobuf:"varint,6,opt,name=successStatus" json:"successStatus,omitempty"`
	DevID         string `protobuf:"bytes,7,opt,name=devID" json:"devID,omitempty"`
}

func (m *History) Reset()                    { *m = History{} }
func (m *History) String() string            { return proto.CompactTextString(m) }
func (*History) ProtoMessage()               {}
func (*History) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *History) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *History) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *History) GetIpAddress() string {
	if m != nil {
		return m.IpAddress
	}
	return ""
}

func (m *History) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *History) GetAccessType() string {
	if m != nil {
		return m.AccessType
	}
	return ""
}

func (m *History) GetSuccessStatus() bool {
	if m != nil {
		return m.SuccessStatus
	}
	return false
}

func (m *History) GetDevID() string {
	if m != nil {
		return m.DevID
	}
	return ""
}

type OAuth struct {
	AppName   string `protobuf:"bytes,1,opt,name=appName" json:"appName,omitempty"`
	AppUserID string `protobuf:"bytes,2,opt,name=appUserID" json:"appUserID,omitempty"`
	AppToken  string `protobuf:"bytes,3,opt,name=appToken" json:"appToken,omitempty"`
}

func (m *OAuth) Reset()                    { *m = OAuth{} }
func (m *OAuth) String() string            { return proto.CompactTextString(m) }
func (*OAuth) ProtoMessage()               {}
func (*OAuth) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *OAuth) GetAppName() string {
	if m != nil {
		return m.AppName
	}
	return ""
}

func (m *OAuth) GetAppUserID() string {
	if m != nil {
		return m.AppUserID
	}
	return ""
}

func (m *OAuth) GetAppToken() string {
	if m != nil {
		return m.AppToken
	}
	return ""
}

type Value struct {
	Value    string `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
	Verified bool   `protobuf:"varint,2,opt,name=verified" json:"verified,omitempty"`
}

func (m *Value) Reset()                    { *m = Value{} }
func (m *Value) String() string            { return proto.CompactTextString(m) }
func (*Value) ProtoMessage()               {}
func (*Value) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Value) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Value) GetVerified() bool {
	if m != nil {
		return m.Verified
	}
	return false
}

type User struct {
	ID           int64      `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	Token        string     `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
	Password     string     `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
	UserName     string     `protobuf:"bytes,4,opt,name=userName" json:"userName,omitempty"`
	LoginHistory []*History `protobuf:"bytes,5,rep,name=loginHistory" json:"loginHistory,omitempty"`
	Phone        *Value     `protobuf:"bytes,6,opt,name=phone" json:"phone,omitempty"`
	Email        *Value     `protobuf:"bytes,7,opt,name=email" json:"email,omitempty"`
	OAuth        *OAuth     `protobuf:"bytes,8,opt,name=oAuth" json:"oAuth,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *User) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *User) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *User) GetLoginHistory() []*History {
	if m != nil {
		return m.LoginHistory
	}
	return nil
}

func (m *User) GetPhone() *Value {
	if m != nil {
		return m.Phone
	}
	return nil
}

func (m *User) GetEmail() *Value {
	if m != nil {
		return m.Email
	}
	return nil
}

func (m *User) GetOAuth() *OAuth {
	if m != nil {
		return m.OAuth
	}
	return nil
}

type BasicAuthRequest struct {
	DeviceID         string `protobuf:"bytes,1,opt,name=deviceID" json:"deviceID,omitempty"`
	ForServiceID     string `protobuf:"bytes,2,opt,name=forServiceID" json:"forServiceID,omitempty"`
	BasicID          string `protobuf:"bytes,3,opt,name=basicID" json:"basicID,omitempty"`
	Password         string `protobuf:"bytes,4,opt,name=password" json:"password,omitempty"`
	RefererServiceID string `protobuf:"bytes,5,opt,name=refererServiceID" json:"refererServiceID,omitempty"`
}

func (m *BasicAuthRequest) Reset()                    { *m = BasicAuthRequest{} }
func (m *BasicAuthRequest) String() string            { return proto.CompactTextString(m) }
func (*BasicAuthRequest) ProtoMessage()               {}
func (*BasicAuthRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *BasicAuthRequest) GetDeviceID() string {
	if m != nil {
		return m.DeviceID
	}
	return ""
}

func (m *BasicAuthRequest) GetForServiceID() string {
	if m != nil {
		return m.ForServiceID
	}
	return ""
}

func (m *BasicAuthRequest) GetBasicID() string {
	if m != nil {
		return m.BasicID
	}
	return ""
}

func (m *BasicAuthRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *BasicAuthRequest) GetRefererServiceID() string {
	if m != nil {
		return m.RefererServiceID
	}
	return ""
}

type OAuthRequest struct {
	DeviceID         string `protobuf:"bytes,1,opt,name=deviceID" json:"deviceID,omitempty"`
	ForServiceID     string `protobuf:"bytes,2,opt,name=forServiceID" json:"forServiceID,omitempty"`
	AppName          string `protobuf:"bytes,3,opt,name=appName" json:"appName,omitempty"`
	AppUserID        string `protobuf:"bytes,4,opt,name=appUserID" json:"appUserID,omitempty"`
	AppToken         string `protobuf:"bytes,5,opt,name=appToken" json:"appToken,omitempty"`
	RefererServiceID string `protobuf:"bytes,6,opt,name=refererServiceID" json:"refererServiceID,omitempty"`
}

func (m *OAuthRequest) Reset()                    { *m = OAuthRequest{} }
func (m *OAuthRequest) String() string            { return proto.CompactTextString(m) }
func (*OAuthRequest) ProtoMessage()               {}
func (*OAuthRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *OAuthRequest) GetDeviceID() string {
	if m != nil {
		return m.DeviceID
	}
	return ""
}

func (m *OAuthRequest) GetForServiceID() string {
	if m != nil {
		return m.ForServiceID
	}
	return ""
}

func (m *OAuthRequest) GetAppName() string {
	if m != nil {
		return m.AppName
	}
	return ""
}

func (m *OAuthRequest) GetAppUserID() string {
	if m != nil {
		return m.AppUserID
	}
	return ""
}

func (m *OAuthRequest) GetAppToken() string {
	if m != nil {
		return m.AppToken
	}
	return ""
}

func (m *OAuthRequest) GetRefererServiceID() string {
	if m != nil {
		return m.RefererServiceID
	}
	return ""
}

type TokenRequest struct {
	DeviceID         string `protobuf:"bytes,1,opt,name=deviceID" json:"deviceID,omitempty"`
	ForServiceID     string `protobuf:"bytes,2,opt,name=forServiceID" json:"forServiceID,omitempty"`
	Token            string `protobuf:"bytes,3,opt,name=token" json:"token,omitempty"`
	RefererServiceID string `protobuf:"bytes,4,opt,name=refererServiceID" json:"refererServiceID,omitempty"`
}

func (m *TokenRequest) Reset()                    { *m = TokenRequest{} }
func (m *TokenRequest) String() string            { return proto.CompactTextString(m) }
func (*TokenRequest) ProtoMessage()               {}
func (*TokenRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *TokenRequest) GetDeviceID() string {
	if m != nil {
		return m.DeviceID
	}
	return ""
}

func (m *TokenRequest) GetForServiceID() string {
	if m != nil {
		return m.ForServiceID
	}
	return ""
}

func (m *TokenRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *TokenRequest) GetRefererServiceID() string {
	if m != nil {
		return m.RefererServiceID
	}
	return ""
}

type Response struct {
	Id     string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Code   int32  `protobuf:"varint,2,opt,name=code" json:"code,omitempty"`
	User   *User  `protobuf:"bytes,3,opt,name=user" json:"user,omitempty"`
	Detail string `protobuf:"bytes,4,opt,name=detail" json:"detail,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Response) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Response) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Response) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Response) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

func init() {
	proto.RegisterType((*History)(nil), "History")
	proto.RegisterType((*OAuth)(nil), "OAuth")
	proto.RegisterType((*Value)(nil), "Value")
	proto.RegisterType((*User)(nil), "User")
	proto.RegisterType((*BasicAuthRequest)(nil), "BasicAuthRequest")
	proto.RegisterType((*OAuthRequest)(nil), "OAuthRequest")
	proto.RegisterType((*TokenRequest)(nil), "TokenRequest")
	proto.RegisterType((*Response)(nil), "Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Publisher API

type Publisher interface {
	Publish(ctx context.Context, msg interface{}, opts ...client.PublishOption) error
}

type publisher struct {
	c     client.Client
	topic string
}

func (p *publisher) Publish(ctx context.Context, msg interface{}, opts ...client.PublishOption) error {
	return p.c.Publish(ctx, p.c.NewPublication(p.topic, msg), opts...)
}

func NewPublisher(topic string, c client.Client) Publisher {
	if c == nil {
		c = client.NewClient()
	}
	return &publisher{c, topic}
}

// Subscriber API

func RegisterSubscriber(topic string, s server.Server, h interface{}, opts ...server.SubscriberOption) error {
	return s.Subscribe(s.NewSubscriber(topic, h, opts...))
}

// Client API for AuthMS service

type AuthMSClient interface {
	RegisterUserName(ctx context.Context, in *BasicAuthRequest, opts ...client.CallOption) (*Response, error)
	RegisterEmail(ctx context.Context, in *BasicAuthRequest, opts ...client.CallOption) (*Response, error)
	RegisterPhone(ctx context.Context, in *BasicAuthRequest, opts ...client.CallOption) (*Response, error)
	RegisterOAuth(ctx context.Context, in *OAuthRequest, opts ...client.CallOption) (*Response, error)
	LoginUserName(ctx context.Context, in *BasicAuthRequest, opts ...client.CallOption) (*Response, error)
	LoginEmail(ctx context.Context, in *BasicAuthRequest, opts ...client.CallOption) (*Response, error)
	LoginPhone(ctx context.Context, in *BasicAuthRequest, opts ...client.CallOption) (*Response, error)
	LoginOAuth(ctx context.Context, in *OAuthRequest, opts ...client.CallOption) (*Response, error)
	ValidateToken(ctx context.Context, in *TokenRequest, opts ...client.CallOption) (*Response, error)
}

type authMSClient struct {
	c           client.Client
	serviceName string
}

func NewAuthMSClient(serviceName string, c client.Client) AuthMSClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "authms"
	}
	return &authMSClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *authMSClient) RegisterUserName(ctx context.Context, in *BasicAuthRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "AuthMS.RegisterUserName", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authMSClient) RegisterEmail(ctx context.Context, in *BasicAuthRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "AuthMS.RegisterEmail", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authMSClient) RegisterPhone(ctx context.Context, in *BasicAuthRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "AuthMS.RegisterPhone", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authMSClient) RegisterOAuth(ctx context.Context, in *OAuthRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "AuthMS.RegisterOAuth", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authMSClient) LoginUserName(ctx context.Context, in *BasicAuthRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "AuthMS.LoginUserName", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authMSClient) LoginEmail(ctx context.Context, in *BasicAuthRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "AuthMS.LoginEmail", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authMSClient) LoginPhone(ctx context.Context, in *BasicAuthRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "AuthMS.LoginPhone", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authMSClient) LoginOAuth(ctx context.Context, in *OAuthRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "AuthMS.LoginOAuth", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authMSClient) ValidateToken(ctx context.Context, in *TokenRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "AuthMS.ValidateToken", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AuthMS service

type AuthMSHandler interface {
	RegisterUserName(context.Context, *BasicAuthRequest, *Response) error
	RegisterEmail(context.Context, *BasicAuthRequest, *Response) error
	RegisterPhone(context.Context, *BasicAuthRequest, *Response) error
	RegisterOAuth(context.Context, *OAuthRequest, *Response) error
	LoginUserName(context.Context, *BasicAuthRequest, *Response) error
	LoginEmail(context.Context, *BasicAuthRequest, *Response) error
	LoginPhone(context.Context, *BasicAuthRequest, *Response) error
	LoginOAuth(context.Context, *OAuthRequest, *Response) error
	ValidateToken(context.Context, *TokenRequest, *Response) error
}

func RegisterAuthMSHandler(s server.Server, hdlr AuthMSHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&AuthMS{hdlr}, opts...))
}

type AuthMS struct {
	AuthMSHandler
}

func (h *AuthMS) RegisterUserName(ctx context.Context, in *BasicAuthRequest, out *Response) error {
	return h.AuthMSHandler.RegisterUserName(ctx, in, out)
}

func (h *AuthMS) RegisterEmail(ctx context.Context, in *BasicAuthRequest, out *Response) error {
	return h.AuthMSHandler.RegisterEmail(ctx, in, out)
}

func (h *AuthMS) RegisterPhone(ctx context.Context, in *BasicAuthRequest, out *Response) error {
	return h.AuthMSHandler.RegisterPhone(ctx, in, out)
}

func (h *AuthMS) RegisterOAuth(ctx context.Context, in *OAuthRequest, out *Response) error {
	return h.AuthMSHandler.RegisterOAuth(ctx, in, out)
}

func (h *AuthMS) LoginUserName(ctx context.Context, in *BasicAuthRequest, out *Response) error {
	return h.AuthMSHandler.LoginUserName(ctx, in, out)
}

func (h *AuthMS) LoginEmail(ctx context.Context, in *BasicAuthRequest, out *Response) error {
	return h.AuthMSHandler.LoginEmail(ctx, in, out)
}

func (h *AuthMS) LoginPhone(ctx context.Context, in *BasicAuthRequest, out *Response) error {
	return h.AuthMSHandler.LoginPhone(ctx, in, out)
}

func (h *AuthMS) LoginOAuth(ctx context.Context, in *OAuthRequest, out *Response) error {
	return h.AuthMSHandler.LoginOAuth(ctx, in, out)
}

func (h *AuthMS) ValidateToken(ctx context.Context, in *TokenRequest, out *Response) error {
	return h.AuthMSHandler.ValidateToken(ctx, in, out)
}

func init() {
	proto.RegisterFile("github.com/tomogoma/authms/proto/authms/authms.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 652 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x55, 0xcb, 0x6e, 0xd3, 0x40,
	0x14, 0xc5, 0x89, 0x9d, 0x26, 0xb7, 0x09, 0x2a, 0xa3, 0x0a, 0x99, 0xaa, 0x42, 0x91, 0xc5, 0x22,
	0xa2, 0x95, 0x23, 0x05, 0x36, 0x2c, 0x8b, 0x82, 0x44, 0x24, 0xa0, 0x68, 0xfa, 0xd8, 0xb0, 0x9a,
	0xc6, 0xb7, 0xc9, 0x88, 0x24, 0x63, 0x3c, 0xe3, 0xa0, 0xfe, 0x05, 0x7f, 0xc2, 0x86, 0x3d, 0x7f,
	0xc0, 0x97, 0xf0, 0x11, 0x68, 0xee, 0xd8, 0x79, 0xf4, 0x8d, 0xd4, 0x55, 0x7c, 0xce, 0xf5, 0xdc,
	0x39, 0xf7, 0xf8, 0xcc, 0x04, 0x5e, 0x8f, 0xa4, 0x19, 0xe7, 0x67, 0xf1, 0x50, 0x4d, 0xbb, 0x46,
	0x4d, 0xd5, 0x48, 0x4d, 0x45, 0x57, 0xe4, 0x66, 0x3c, 0xd5, 0xdd, 0x34, 0x53, 0x46, 0x95, 0xc0,
	0xfd, 0xc4, 0xc4, 0x45, 0xbf, 0x3d, 0xd8, 0x78, 0x2f, 0xb5, 0x51, 0xd9, 0x05, 0x7b, 0x0c, 0x95,
	0x41, 0x3f, 0xf4, 0xda, 0x5e, 0xa7, 0xca, 0x2b, 0x83, 0x3e, 0x7b, 0x0a, 0xb5, 0x5c, 0x63, 0x36,
	0xe8, 0x87, 0x15, 0xe2, 0x0a, 0xc4, 0x76, 0xa1, 0x21, 0xd3, 0x83, 0x24, 0xc9, 0x50, 0xeb, 0xb0,
	0xda, 0xf6, 0x3a, 0x0d, 0xbe, 0x24, 0x18, 0x03, 0x3f, 0x11, 0x06, 0x43, 0x9f, 0x0a, 0xf4, 0xcc,
	0x9e, 0x03, 0x88, 0xe1, 0x10, 0xb5, 0x3e, 0xbe, 0x48, 0x31, 0x0c, 0xa8, 0xb2, 0xc2, 0xb0, 0x17,
	0xd0, 0xd2, 0x39, 0xc1, 0x23, 0x23, 0x4c, 0xae, 0xc3, 0x5a, 0xdb, 0xeb, 0xd4, 0xf9, 0x3a, 0xc9,
	0xb6, 0x21, 0x48, 0x70, 0x3e, 0xe8, 0x87, 0x1b, 0xd4, 0xc0, 0x81, 0xe8, 0x0b, 0x04, 0x87, 0x07,
	0xb9, 0x19, 0xb3, 0x10, 0x36, 0x44, 0x9a, 0x7e, 0x12, 0x53, 0xa4, 0x19, 0x1a, 0xbc, 0x84, 0x56,
	0xb0, 0x48, 0xd3, 0x93, 0xe5, 0x2c, 0x0d, 0xbe, 0x24, 0xd8, 0x0e, 0xd4, 0x45, 0x9a, 0x1e, 0xab,
	0xaf, 0x38, 0x2b, 0xa6, 0x59, 0xe0, 0xe8, 0x0d, 0x04, 0xa7, 0x62, 0x92, 0xa3, 0xdd, 0x7b, 0x6e,
	0x1f, 0x8a, 0xd6, 0x0e, 0xd8, 0xa5, 0x73, 0xcc, 0xe4, 0xb9, 0xc4, 0x84, 0xfa, 0xd6, 0xf9, 0x02,
	0x47, 0x7f, 0x3d, 0xf0, 0xed, 0x0e, 0x57, 0x6c, 0xdd, 0x86, 0xc0, 0xd0, 0x66, 0x4e, 0x89, 0x03,
	0xb6, 0x55, 0x2a, 0xb4, 0xfe, 0xae, 0xb2, 0xa4, 0x54, 0x51, 0x62, 0x5b, 0xb3, 0xd6, 0xd3, 0x68,
	0xce, 0xd6, 0x05, 0x66, 0xfb, 0xd0, 0x9c, 0xa8, 0x91, 0x9c, 0x15, 0x1f, 0x31, 0x0c, 0xda, 0xd5,
	0xce, 0x66, 0xaf, 0x1e, 0x17, 0x98, 0xaf, 0x55, 0xd9, 0x2e, 0x04, 0xe9, 0x58, 0xcd, 0x90, 0x0c,
	0xde, 0xec, 0xd5, 0x62, 0x9a, 0x8e, 0x3b, 0xd2, 0x56, 0x71, 0x2a, 0xe4, 0x84, 0x0c, 0x5e, 0xa9,
	0x12, 0x69, 0xab, 0xca, 0x1a, 0x1d, 0xd6, 0x8b, 0x2a, 0xd9, 0xce, 0x1d, 0x19, 0xfd, 0xf2, 0x60,
	0xeb, 0xad, 0xd0, 0x72, 0x48, 0x24, 0x7e, 0xcb, 0x51, 0x1b, 0x2b, 0x3c, 0xc1, 0xb9, 0x1c, 0x62,
	0x61, 0x40, 0x83, 0x2f, 0x30, 0x8b, 0xa0, 0x79, 0xae, 0xb2, 0x23, 0xcc, 0x8a, 0xba, 0x73, 0x63,
	0x8d, 0xb3, 0x9f, 0xf4, 0xcc, 0xf6, 0x1c, 0xf4, 0x0b, 0x4f, 0x4a, 0xb8, 0x66, 0x97, 0x7f, 0xc9,
	0xae, 0x97, 0xb0, 0x95, 0xe1, 0x39, 0x66, 0xb8, 0xd2, 0xdd, 0x65, 0xee, 0x0a, 0x1f, 0xfd, 0xf1,
	0xa0, 0x79, 0xf8, 0xc0, 0x92, 0xcb, 0x14, 0x56, 0x6f, 0x49, 0xa1, 0x7f, 0x5b, 0x0a, 0x83, 0xf5,
	0x14, 0x5e, 0x3b, 0x50, 0xed, 0x86, 0x81, 0x7e, 0x78, 0xd0, 0xa4, 0x55, 0x0f, 0x35, 0xd0, 0x22,
	0xae, 0xd5, 0xd5, 0xb8, 0x5e, 0x27, 0xc9, 0xbf, 0x41, 0x92, 0x80, 0x3a, 0x47, 0x9d, 0xaa, 0x99,
	0x46, 0x7b, 0x18, 0x64, 0x52, 0xe8, 0xa8, 0xc8, 0xc4, 0xde, 0x16, 0x43, 0x95, 0x20, 0xed, 0x1c,
	0x70, 0x7a, 0x66, 0xcf, 0xc0, 0xb7, 0xf1, 0xa6, 0x0d, 0x37, 0x7b, 0x41, 0x6c, 0x1d, 0xe2, 0x44,
	0xd9, 0x2b, 0x29, 0x41, 0x63, 0x23, 0xea, 0x36, 0x2b, 0x50, 0xef, 0x67, 0x15, 0x6a, 0xf6, 0x2b,
	0x7e, 0x3c, 0x62, 0x3d, 0xd8, 0xe2, 0x38, 0x92, 0xda, 0x60, 0x76, 0x52, 0x1e, 0x92, 0x27, 0xf1,
	0xe5, 0x68, 0xee, 0x34, 0xe2, 0x52, 0x53, 0xf4, 0x88, 0x75, 0xa1, 0x55, 0xae, 0x79, 0x47, 0x59,
	0xff, 0x8f, 0x05, 0x9f, 0xe9, 0xe8, 0xdc, 0xb5, 0x60, 0x6f, 0xb9, 0xc0, 0xdd, 0x56, 0xad, 0xf8,
	0xf0, 0xb6, 0xee, 0x1f, 0xec, 0xa9, 0xbd, 0xb7, 0xfe, 0x7d, 0x00, 0x5a, 0x70, 0x3f, 0xf1, 0xe5,
	0xdb, 0xf7, 0x53, 0xde, 0x29, 0xde, 0xbe, 0x5b, 0xf6, 0x1e, 0xb4, 0x4e, 0xc5, 0x44, 0xda, 0x1b,
	0xdf, 0xe5, 0xb6, 0x15, 0xaf, 0x26, 0x71, 0xed, 0xe5, 0xb3, 0x1a, 0xfd, 0xff, 0xbc, 0xfa, 0x17,
	0x00, 0x00, 0xff, 0xff, 0x70, 0x8e, 0x6e, 0x0f, 0xb7, 0x06, 0x00, 0x00,
}
